services:
  it-agent-api:
    image: registry.gitlab.com/chenkuanchung810905/llmops-it-agent:latest
    container_name: it-agent-staging
    ports:
      - "8000:8000"
    restart: always 
    environment:
      - ENV=staging
      - GEMINI_API_KEY=${GEMINI_API_KEY}